### ISSUE TITLE
[BUG] Money stocking

### ISSUE THREAD

**Issue by langw0ww** [CS-GEJMERZY/VIP-Plugin#33]
Money are not stacking correctly. After round ends at the next round start you have to buy and sell a gun to take all money.

Also I think i'm getting segmentation fault sometimes.

**Comment by langw0ww** [comment]
Also, if i have 110HP and use medkit, it set 100HP . Maybe it would be good to cannot use medkit if u don't have under 100HP.
Also this plugin have segmentation fault, I disabled plugin 1 by 1 and this plugin is problem.

**Comment by HackerDevs** [comment]
I'll take a closer look at the money issue. My suspicion is that it might be caused by calling the PlayerSpawnn_TimerGive function with a 1-second delay.

The healthshot_allow_use_at_full cvars address this situation by blocking healthshot usage. I'll look further into it and keep you updated.

Regarding the crash:

- Can you provide more details about when it occurs?
- Have you encountered any error logs?
- Are there any unusual features enabled, such as fast plant/defuse?
- What are the specifications of your OS, metamod, CSS, and plugin versions?

**Comment by langw0ww** [comment]
It occurs sometimes when 2 vips are bunnyhoping, at changing map and sometimes for nothig, just crash.
I get only "Segmentation fault (core dumped)"
Yes, fast plant/defuse is enabled, also: bunnyhop, extrajump, colored smoke;
Using centos ubuntu and last verios of metamod, css and plugin version.

**Comment by langw0ww** [comment]
https://i.imgur.com/nOzcMut.png
this i got today in game console and segmentation fault (core dump) in server console

**Comment by HackerDevs** [comment]
> https://i.imgur.com/nOzcMut.png this i got today in game console and segmentation fault (core dump) in server console
That just says your client is trying to connect to the server.

Please check if this version solves the problem
https://github.com/CS-GEJMERZY/VIP-Plugin/actions/runs/8854442449/artifacts/1452338191

**Comment by langw0ww** [comment]
Works for now.
Another thing that i didnt understand. How to add vip groups if to be vip you need to have "@vip-plugin/vip". Can you give me an example of script config for 3 vip groups?

**Comment by HackerDevs** [comment]
I realized that I may have been calling ```SetStateChanged``` on the wrong class. Additionally, I redesigned the player spawn event to eliminate delays by removing timers and instantly assigning perks to players upon spawning.
Please try the latest build artifact in [refactor/spawn-event](https://github.com/CS-GEJMERZY/VIP-Plugin/tree/refactor/spawn-event) branch. 
https://github.com/CS-GEJMERZY/VIP-Plugin/actions/runs/9046356305/artifacts/1493980845
